---
- hosts: test_servers
  tasks:
    - name: create directory
      file:
        path: /Users/kentaro_honda/tmp
        state: directory
        owner: kentaro_honda
        mode: 0755
    - name: copy file
      copy:
        src: /Users/kentaro_honda/projects/effective_ansible/sec2/test.txt
        dest: /Users/kentaro_honda/tmp
        owner: kentaro_honda
        mode: 0644
