---
- hosts: test_servers
  remote_user: ec2-user # ログインユーザの指定

  tasks:
    - name: create directory
      file:
        path: /home/ec2-user/tmp
        state: directory
        owner: ec2-user
        mode: 0755
    - name: copy file
      copy:
        src: /Users/kentaro_honda/projects/effective_ansible/sec2/test.txt
        dest: /home/ec2-user/tmp
        owner: ec2-user
        mode: 0644
